spring:
  jpa:
    database-platform: H2
    properties:
      hibernate:
        physical_naming_strategy: org.it.discovery.training.hibernate.naming.UpperCaseNamingStrategy
logging:
  level:
    org:
      hibernate:
        SQL: debug
        type: trace